// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthdv0D-9kNJ3yroaAJh9fHDjnjYmifg0',
    appId: '1:667147258562:web:c9ebb0d7e6f8b10b28c95b',
    messagingSenderId: '667147258562',
    projectId: 'elegant-media-project-f260e',
    authDomain: 'elegant-media-project-f260e.firebaseapp.com',
    storageBucket: 'elegant-media-project-f260e.appspot.com',
    measurementId: 'G-GKV0HWF8K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zaDSfOYAPfplTIWX3CFaDx4XYyMRXcw',
    appId: '1:667147258562:android:f1ca6fe153691a2628c95b',
    messagingSenderId: '667147258562',
    projectId: 'elegant-media-project-f260e',
    storageBucket: 'elegant-media-project-f260e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoz-xXG0sXgj1SkJGcMrzWFoWtEOeQ4xI',
    appId: '1:667147258562:ios:30c3697afa47924a28c95b',
    messagingSenderId: '667147258562',
    projectId: 'elegant-media-project-f260e',
    storageBucket: 'elegant-media-project-f260e.appspot.com',
    iosBundleId: 'com.example.testCodeFlutterFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBthdv0D-9kNJ3yroaAJh9fHDjnjYmifg0',
    appId: '1:667147258562:web:4bb8a57900872d4628c95b',
    messagingSenderId: '667147258562',
    projectId: 'elegant-media-project-f260e',
    authDomain: 'elegant-media-project-f260e.firebaseapp.com',
    storageBucket: 'elegant-media-project-f260e.appspot.com',
    measurementId: 'G-5KDY5VHFYP',
  );

}